### PR TITLE
compatibility with ember 2.x

### PR DESCRIPTION
**Pull request by aklkv**
I have fixed some depreciation warnings in ember 2.1, can you please merge it

### CODE REVIEW

**Comment by miguelcobain** [comment]
Thanks a lot!

**Comment by aklkv** [comment]
No problem! Do you know how fast npm will catch up to this changes? I wan to you this plugin in my project

**Comment by miguelcobain** [comment]
@aklkv version 0.0.4 should be published and ready to use.

**Comment by aklkv** [comment]
@miguelcobain awesome! thanks

**Pull request merged**
